"""Rapoartele finale ale fazei de recensamant + coada S1-S7: census_report.md, external_review_report.md, strategies/ranking, corectie globala Holm-Bonferroni pe toate testele primare ale noptii, terminal_summary.txt, SHA256SUMS."""
import json,os,glob,hashlib,time,subprocess
AC="research/overnight_20260905/atomic_census"; ST="research/overnight_20260905/strategies"; ON="research/overnight_20260905"
def J(p): return json.load(open(p)) if os.path.exists(p) else None
def sha(p): return hashlib.sha256(open(p,"rb").read()).hexdigest()
cen=J(f"{AC}/census_results.json"); man=J(f"{AC}/census_manifest.json"); ind=J(f"{AC}/independent_census_results.json"); rec=J(f"{AC}/reconciliation.json"); per=J(f"{AC}/arber_persistence_results.json"); slow=J(f"{AC}/slow_capture_results.json"); hl=J(f"{AC}/opportunity_half_life.json"); ll=J(f"{AC}/lead_lag_diagnostics.json"); adv=J(f"{AC}/adversarial_tests.json"); prop=J(f"{AC}/property_tests.json"); ex=J(f"{AC}/executor_structure.json")
Sres={k:J(f"{ST}/{k}_results.json") for k in ("s1","s2","s3","s4","s5","s6","s7")}; H={h:J(f"{ON}/{n}_results.json") for h,n in (("H1","h1_cohort_rotation"),("H2","h2_seller_overhang"),("H3","h3_selective_buyer"))}
def f(v,nd=5): return "n/a" if v is None else (f"{v:.{nd}f}" if isinstance(v,float) else str(v))
# ---- corectie globala Holm-Bonferroni pe toate testele primare ale noptii ----
tests=[]
for h in ("H1","H2","H3"):
    b=(H[h] or {}).get("bootstrap") or {}; tests.append(dict(test=h,p_raw=b.get("p_raw_one_sided"),verdict=(H[h] or {}).get("verdict")))
tests.append(dict(test="EXECUTED_ARB_MECHANISM",p_raw=((cen or {}).get("bootstrap_token_day") or {}).get("p_le_0"),verdict=(cen or {}).get("verdict")))
tests.append(dict(test="ARBER_PERSISTENCE_V1",p_raw=None,verdict=(per or {}).get("verdict")))
tests.append(dict(test="SLOW_CAPTURE_V1",p_raw=None,verdict=((slow or {}).get("evaluation") or {}).get("verdict")))
for k in ("s1","s2","s3","s4","s5"):
    r=Sres[k] or {}; tests.append(dict(test=k.upper(),p_raw=((r.get("bootstrap") or {}).get("p_le_0")),verdict=r.get("verdict")))
tests.append(dict(test="S6",p_raw=None,verdict=(Sres["s6"] or {}).get("verdict"))); tests.append(dict(test="S7",p_raw=None,verdict=(Sres["s7"] or {}).get("verdict")))
m=len(tests); withp=sorted([t for t in tests if t["p_raw"] is not None],key=lambda t:t["p_raw"]); cur=0.0
for i,t in enumerate(withp): cur=max(cur,min(1.0,(m-i)*t["p_raw"])); t["p_holm"]=cur
for t in tests:
    if t["p_raw"] is None: t["p_holm"]=None
MT=dict(method="Holm-Bonferroni pe toate testele primare ale noptii (m = %d: H1-H3, EXECUTED_ARB_MECHANISM, ARBER_PERSISTENCE, SLOW_CAPTURE, S1-S7)"%m,m=m,tests=tests,any_pass_after_correction=any((t.get("p_holm") is not None and t["p_holm"]<0.05 and str(t.get("verdict","")).startswith(("PASS","EXECUTED_ARB_MECHANISM_CONFIRMED"))) for t in tests))
json.dump(MT,open(f"{ON}/global_multiple_testing.json","w"),indent=1)
# ---- census report ----
np_=cen.get("net_PRIMARY") or {}; L=[f"# EXECUTED_CROSS_POOL_ARB_CENSUS — raport (POST_HOC_HISTORICAL_RESEARCH)","",f"Spec inghetat sha256 {man['CENSUS_SPEC_SHA256']}. Swap-uri scanate {man['TOTAL_SWAP_EVENTS_SCANNED']:,}; tranzactii cu >= 2 swap-uri {man['multi_swap_transactions']:,}; grupuri candidate {man['candidate_groups']:,} in {man['CANDIDATE_SIGNATURES']:,} semnaturi; cicluri EXACT (base conservat) {man['EXACT_BASE_CONSERVED_CYCLES']}; DUST {man['DUST_CYCLES']}; respinse: {json.dumps(man['rejected'])}. Executori (hash) {man['UNIQUE_USERS_HASHED']}, token-uri {man['UNIQUE_TOKENS']}, perechi de pool-uri {man['UNIQUE_POOL_PAIRS']}, zile {man['DATES']}, pe zi {man['by_day']}; toate ciclurile au exact 2 swap-uri si o singura tranzactie per ciclu.","",
  f"## Economie realizata (din sumele executate; cost complet per ciclu)","| Scenariu | N | EV SOL | mediana | PF | win | total | ex-best-1 | ex-best-3 | ex-best-1% |","|---|---|---|---|---|---|---|---|---|---|"]
for k in ("net_PRIMARY","net_STRESS_1","net_STRESS_2","net_NEW_ACCOUNT_STRESS","gross"):
    s=cen.get(k) or {}; L.append(f"| {k} | {s.get('N')} | {f(s.get('EV'))} | {f(s.get('median'),6)} | {f(s.get('PF'),2)} | {f(s.get('win_rate'),3)} | {f(s.get('total'),4)} | {f(s.get('EX_BEST_1'))} | {f(s.get('EX_BEST_3'))} | {f(s.get('EX_BEST_1PCT'))} |")
L+=["",f"Pe zi (PRIMARY): {json.dumps({d:(v or {}).get('EV') for d,v in (cen.get('by_day') or {}).items()})}. Cota top executor {f(cen.get('top_user_share'),3)}, top token {f(cen.get('top_token_share'),3)}, top pereche {f(cen.get('top_pool_pair_share'),3)}; executori unici {cen.get('unique_users')}; cicluri per executor {json.dumps(cen.get('cycles_per_user'))}; marime mediana platita {f((cen.get('sizes_sol') or {}).get('median_paid'),4)} SOL (p90 {f((cen.get('sizes_sol') or {}).get('p90_paid'),4)}); atomic din ordinea evenimentelor: {cen.get('atomic_from_event_order')}.",f"Bootstrap 10.000: user x zi CI95 {cen.get('bootstrap_user_day',{}).get('CI95')}; token x zi CI95 {cen.get('bootstrap_token_day',{}).get('CI95')}.",f"Poarta: {json.dumps(cen.get('gate'))} => **{cen.get('verdict')}** (mecanismul executat este real dar profitul este concentrat intr-un singur executor/token si intr-o minoritate de cicluri: 8,2 % castigatoare, mediana negativa).","",
  f"## Verificare independenta\n{json.dumps({k:v for k,v in rec.items() if k!='sample_100'},default=str)[:1500]}; esantion 100 semnaturi: {rec['sample_100']['field_agreement']}/{rec['sample_100']['n']} campuri identice. INDEPENDENT_IMPLEMENTATIONS_AGREE = {rec['INDEPENDENT_IMPLEMENTATIONS_AGREE']}.","",
  f"## Structura executorilor\n{json.dumps({k:v for k,v in ex.items() if k!='executors_hashed'},default=str)[:1500]}","",f"## ARBER_PERSISTENCE_V1\n{json.dumps({k:v for k,v in per.items() if k!='spec'},default=str)[:900]}","",
  f"## SLOW_CAPTURE_OF_EXECUTED_ARB_V1\n{json.dumps({k:v for k,v in slow.items() if k in ('population','engine','evaluation','statuses','predicted_vs_realized')},default=str)[:1500]}\nInterpretare: in populatia inghetata (127 pool-uri stricte cu VQ si taxe valide) nu exista nicio stare de decizie cu profit predicted > 0 dupa taxe (25/5/0 pe fiecare leg) si cost; ciclurile executate de boti se concentreaza in pool-uri din afara acestei populatii (orientare inversa, VQ neverificabil sau cu scheme de taxe anormale) — 5.444 grupuri candidate respinse pentru orientare non-stricta.","",
  f"## Half-life (descriptiv)\n{json.dumps(hl,default=str)[:800]}","",f"## Lead/lag (descriptiv)\n{json.dumps(ll,default=str)[:900]}","",f"## Falsificare\n{json.dumps({k:v for k,v in adv.items() if k in ('base','ex_top1pct','ex_top3','leave_one_day_out','leave_one_token_out_min_EV','leave_one_executor_out_min_EV','cost_stresses','user_shuffle_within_day_token','negative_conservation_anomalies')},default=str)[:1800]}\nTeste de proprietate/fuzz: {prop.get('PASS')} ({prop.get('fuzz_cases')} cazuri, {len(prop.get('violations',[]))} incalcari)."]
open(f"{AC}/census_report.md","w").write("\n".join(L))
# ---- ranking + external review report ----
def sv(k): r=Sres[k] or {}; t=r.get("test") or r.get("filtered") or {}; return dict(verdict=r.get("verdict"),N=t.get("N") if isinstance(t,dict) else None,EV=t.get("EV") if isinstance(t,dict) else None,PF=t.get("PF") if isinstance(t,dict) else None)
rank=[dict(name="EXECUTED bot cycles (observed, not accessible)",realism="observat real; necesita infrastructura de bot (aceeasi tranzactie, competitie in acelasi slot 100 %)",evidence=f"N=500, EV {f(np_.get('EV'))} SOL, PF {f(np_.get('PF'),1)}, concentrare 84 %",category="actual bot profits observed"),
      dict(name="SLOW_CAPTURE_V1",realism="ordinar +3 sloturi",evidence="0 stari profitabile in populatia inghetata",category="inaccessible / no verified edge"),
      dict(name="S6 router",realism="executie",evidence=(Sres["s6"] or {}).get("verdict"),category="execution-cost improvement (not confirmed)"),dict(name="S7 toxicity filter",realism="filtru",evidence=(Sres["s7"] or {}).get("verdict"),category="loss-avoidance filter (no value)")]+[dict(name=k.upper(),realism="directional, +3 sloturi",evidence=sv(k),category="failed / insufficient") for k in ("s1","s2","s3","s4","s5")]+[dict(name=h,realism="directional (intrare la D)",evidence=(H[h] or {}).get("verdict"),category="failed / insufficient") for h in ("H1","H2","H3")]
ER=["# EXTERNAL REVIEW REPORT — overnight 2026-09-05 (POST_HOC_HISTORICAL_RESEARCH)","",f"Commit: {subprocess.run(['git','rev-parse','HEAD'],capture_output=True,text=True).stdout.strip()}. RPC 0, date noi 0, colectoare 0, live 0.","","## Clasificare finala","| # | Strategie | Realism executie | Dovezi | Categorie |","|---|---|---|---|---|"]+[f"| {i+1} | {r['name']} | {r['realism']} | {json.dumps(r['evidence'],default=str)[:160]} | {r['category']} |" for i,r in enumerate(rank)]
ER+=["",f"## Corectie globala\n{MT['method']}; niciun test primar nu trece dupa corectie: {not MT['any_pass_after_correction']}.","","## Distinctii cerute","- profituri reale ale botilor observate: 500 cicluri, +12,59 SOL net total, 84 % de la un singur executor/token, castig in 8,2 % din cicluri; competitie in acelasi slot in 100 % din cazuri;","- profituri istorice teoretic executabile cu infrastructura obisnuita: niciunul verificat (slow capture 0 stari; S2 0 reziduuri; S1/S3/S4/S5 FAIL/INSUFFICIENT);","- profituri inaccesibile fara infrastructura premium: ciclurile executate (aceeasi tranzactie, primul slot);","- candidati directionali paper: niciunul;","- imbunatatiri de cost de executie: niciuna confirmata (pool-ul implicit este deja cel mai bun in >99 % din decizii; impartirea costa mai mult decat economiseste);","- filtre de conservare a capitalului: niciunul cu valoare (S7 NO_VALUE);","- strategii esuate: H1, H3, S1 (FAIL); H2, S2, S3, S4, S5 (INSUFFICIENT_CLEAN_SAMPLE); ARBER_PERSISTENCE (INSUFFICIENT); SLOW_CAPTURE (NO_VERIFIED_EDGE); EXECUTED_ARB_MECHANISM (NOT_CONFIRMED by concentration).","",f"## Blocante nerezolvate\n- programul token al mint-urilor (owner) neverificat (fara RPC);\n- Deposit/Withdraw nedecodate de colector (ancore folosite in loc);\n- transactionIndex absent (worst-of pre/post);\n- istoricul creatorilor limitat la 43 h de banda;\n- populatia slow-capture exclude pool-urile cu orientare inversa (unde s-au executat majoritatea ciclurilor reale).","","READY_FOR_FRESH_FORWARD_TEST = NO; READY_FOR_LIVE_TRADING = NO."]
open(f"{AC}/external_review_report.md","w").write("\n".join(ER)); json.dump(rank,open(f"{ST}/final_ranking.json","w"),indent=1,default=str)
commit=subprocess.run(["git","rev-parse","HEAD"],capture_output=True,text=True).stdout.strip(); bu=cen.get("bootstrap_user_day",{}); bt=cen.get("bootstrap_token_day",{}); sl=(slow or {}).get("evaluation") or {}
T=["OVERNIGHT_ATOMIC_CENSUS_COMPLETE = YES","DEADLINE_REACHED = NO",f"CURRENT_COMMIT = {commit}","NEW_DATA_ACCESSED = NO","RPC_CALLS = 0",f"TOTAL_SWAPS_SCANNED = {man['TOTAL_SWAP_EVENTS_SCANNED']}",f"EXACT_ATOMIC_CYCLES = {man['EXACT_BASE_CONSERVED_CYCLES']}",f"UNIQUE_EXECUTORS = {man['UNIQUE_USERS_HASHED']}",f"UNIQUE_TOKENS = {man['UNIQUE_TOKENS']}",f"OBSERVED_ARB_NET_EV = {f(np_.get('EV'))} SOL (mediana {f(np_.get('median'),6)}, win {f(np_.get('win_rate'),3)})",f"OBSERVED_ARB_PF = {f(np_.get('PF'),1)}",f"OBSERVED_ARB_CI95 = user x zi {bu.get('CI95')}; token x zi {bt.get('CI95')}",f"OBSERVED_ARB_MECHANISM_VERDICT = {cen.get('verdict')}",f"ARBER_PERSISTENCE_VERDICT = {per.get('verdict')}",f"SLOW_CAPTURE_N = {sl.get('N',0)}",f"SLOW_CAPTURE_EV = {f((sl.get('stats') or {}).get('EV'))}",f"SLOW_CAPTURE_PF = {f((sl.get('stats') or {}).get('PF'),3)}",f"SLOW_CAPTURE_CI95 = {sl.get('CI95_token_day')}",f"SLOW_CAPTURE_VERDICT = {sl.get('verdict')}",f"OPPORTUNITY_MEDIAN_LIFETIME_SLOTS = {hl.get('median_lifetime_slots')} (0 stari profitabile in populatia inghetata)",f"SURVIVAL_AT_3_SLOTS = {hl.get('survival_pct',{}).get('3')}",f"SURVIVAL_AT_5_SLOTS = {hl.get('survival_pct',{}).get('5')}",f"TOP_EXECUTOR_PROFIT_SHARE = {f(cen.get('top_user_share'),3)}",f"TOP_TOKEN_PROFIT_SHARE = {f(cen.get('top_token_share'),3)}",f"INDEPENDENT_IMPLEMENTATIONS_AGREE = {rec['INDEPENDENT_IMPLEMENTATIONS_AGREE']}",f"ADVERSARIAL_TESTS = ex-best-1% EV {f((adv.get('ex_top1pct') or {}).get('EV'))}, ex-best-3 {f((adv.get('ex_top3') or {}).get('EV'))}, leave-one-executor-out min EV {f(adv.get('leave_one_executor_out_min_EV'))}, user-shuffle p {adv.get('user_shuffle_within_day_token',{}).get('p_perm_ge_obs')}, property tests PASS={prop.get('PASS')}","NEW_DATA_ACCESSED = NO","LIVE_TRADING_ENABLED = NO","READY_FOR_FRESH_FORWARD_TEST = NO","READY_FOR_LIVE_TRADING = NO",f"FINAL_REPORT_PATH = {AC}/external_review_report.md","READY_FOR_EXTERNAL_REVIEW = YES","",
   f"STRATEGIES_COMPLETED = 7/7"]+[f"{k.upper()}_VERDICT = {(Sres[k] or {}).get('verdict')}" for k in ("s1","s2","s3","s4","s5","s6","s7")]+["BEST_ACTUAL_EXECUTED_PATTERN = cicluri atomice 2-swap cross-pool (500 observate; 84 % profit de la un executor/token; inaccesibile fara infrastructura de bot)","BEST_ACCESSIBLE_PAPER_CANDIDATE = NONE","BEST_EXECUTION_IMPROVEMENT = NONE (S6 NOT_CONFIRMED)","BEST_CAPITAL_PRESERVATION_FILTER = NONE (S7 NO_VALUE)","REQUIRED_CAPITAL_SOL = n/a (niciun candidat); referinta 0,10-0,25 SOL per tranzactie + rezerva de revert","ORDINARY_INFRASTRUCTURE_SUFFICIENT = NO pentru ciclurile observate; nicio strategie accesibila verificata",f"GLOBAL_CORRECTION_METHOD = {MT['method']}","UNRESOLVED_BLOCKERS = token program neverificat; Deposit/Withdraw nedecodate; transactionIndex absent; istoric creatori 43 h; pool-uri cu orientare inversa excluse din motor","READY_FOR_FRESH_FORWARD_TEST = NO","READY_FOR_LIVE_TRADING = NO"]
open(f"{AC}/terminal_summary.txt","w").write("\n".join(T))
for d in (AC,ST):
    files=sorted(p for p in glob.glob(f"{d}/*") if os.path.isfile(p) and not p.endswith("SHA256SUMS")); open(f"{d}/SHA256SUMS","w").write("".join(f"{sha(p)}  {os.path.basename(p)}\n" for p in files))
print("\n".join(T))
