"""Genereaza data_dictionary.csv, rapoartele H1-H3 (md), final_report.md, terminal_summary.txt, README.md si SHA256SUMS pentru research/overnight_20260905 (fara randuri brute, fara portofele)."""
import json,csv,os,hashlib,time,glob,subprocess
OUT="research/overnight_20260905"
def sha(p): return hashlib.sha256(open(p,"rb").read()).hexdigest()
def fmt(v,nd=5): return ("n/a" if v is None else (f"{v:.{nd}f}" if isinstance(v,float) else str(v)))
R={h:json.load(open(f"{OUT}/{n}_results.json")) for h,n in (("H1","h1_cohort_rotation"),("H2","h2_seller_overhang"),("H3","h3_selective_buyer"))}; U=json.load(open(f"{OUT}/unconditional_results.json")); MT=json.load(open(f"{OUT}/multiple_testing_summary.json")); AD=json.load(open(f"{OUT}/adversarial_review.json")); LT=json.load(open(f"{OUT}/leakage_tests.json")); PM=json.load(open(f"{OUT}/cohort_panel_manifest.json")); OM=json.load(open(f"{OUT}/outcomes_manifest.json")); IM=json.load(open(f"{OUT}/integrity_manifest.json")); TH=json.load(open(f"{OUT}/thresholds_frozen.json"))
names={"H1":"COHORT_ROTATION_V2","H2":"SELLER_OVERHANG_DECAY_V2","H3":"SELECTIVE_BUYER_QUALITY_V1"}
# data dictionary
DD=[("panel","mint","string","adresa mint (LOCAL; nepublicat)","CreateEvent","-","KEY"),("panel","day","date","zi UTC a CompleteEvent","-","-","META"),("panel","T0_ts","int s","ts on-chain CreatePoolEvent","CreatePoolEvent","-","PIT"),("panel","D","int s","T0_ts+60 (decizie)","spec","-","PIT"),("panel","cohort_size","int","portofele cu INVENTORY_PROXY>0 din trade-urile de curba","curba","<Complete","PIT"),("panel","inventory_proxy_total","int tokeni bruti","suma inventarelor reconstruite din trade-uri (NU solduri ajustate cu transferuri)","curba","<Complete","PIT"),("panel","creator_inventory_share","float","inventar creator / total","curba","<Complete","PIT"),("panel","feature_max_ts","int s","cel mai mare ts al evenimentelor de pool folosite (< D)","pool","<D","PIT"),("panel","last_contributing_slot","int","ultimul slot contribuitor","pool","<D","PIT"),("panel","n_post_swaps","int","evenimente pool in [T0,D)","pool","<D","PIT"),("panel","n_post_buyers / n_post_sellers","int","cumparatori/vanzatori distincti","pool","<D","PIT"),("panel","n_post_only_buyers","int","cumparatori care NU sunt in cohorta pre-migrare","pool+curba","<D","PIT"),("panel","n_incumbent_sellers","int","vanzatori din cohorta","pool+curba","<D","PIT"),("panel","buy_quote / sell_quote","float SOL","flux quote","pool","<D","PIT"),("panel","incumbent_sell_quote / incumbent_sell_share","float","vanzari ale cohortei; cota din fluxul total","pool+curba","<D","PIT"),("panel","post_only_buy_quote / post_only_buy_share","float","cumparari ale portofelelor noi","pool","<D","PIT"),("panel","top1_buy_share / top3_buy_share / hhi_buy","float","concentratia fluxului de cumparare pe portofel","pool","<D","PIT"),("panel","inc_sell_0_30 / inc_sell_30_60 / decay_ratio","float SOL","intensitatea vanzarilor incumbente pe subferestre; raport 30-60/0-30","pool+curba","<D","PIT"),("panel","remaining_inventory_proxy","float","INVENTORY_PROXY ramas al cohortei / total T0","pool+curba","<D","PIT"),("panel","largest_incumbent_remaining_share","float","cel mai mare inventar ramas / supply proxy 1e15","pool+curba","<D","PIT"),("panel","buyers_prior","list (n_prior_mints, n_prior_24h, quote)","selectivitatea cumparatorilor post-only din istoricul ANTERIOR deciziei (mint-uri distincte tranzactionate cu first_ts < D)","tape intreg","<D","PIT"),("panel","median_prior_mints / median_prior_mints_24h","float","mediana selectivitatii","tape","<D","PIT"),("panel","liquidity_sol","float SOL","rezerva reala de quote la ultima stare < D","pool","<D","PIT (control)"),("panel","ret_bp","float bp","pret la D vs deschidere","pool","<D","PIT (control)"),("panel","vol_bp","float bp","dev. std. a log-randamentelor intre stari","pool","<D","PIT (control)"),("panel","buy_flow_sol_per_s","float","intensitatea cumpararilor","pool","<D","PIT (control)"),
    ("outcomes","primary.status","string","OK sau motivul excluderii (ENTRY_STATE_UNANCHORED, CHAIN_BREAK_IN_HOLD, FEE_UNRESOLVED_*, NO_EXIT_STATE ...)","executie","dupa D","OUTCOME"),("outcomes","primary.entry_ts/exit_ts","float s","intrare la D (stare ancorata dupa toate evenimentele ts<=D); iesire la intrare+60 s","executie","dupa D","OUTCOME"),("outcomes","primary.B / quote_spent / sell_out","int","cumparare exact-B sub bugetul 0,25 SOL; vanzare exact B cu overlay","executie","dupa D","OUTCOME"),("outcomes","primary.pnl_sol","float SOL","sell_out - quote_spent - 0,00021 SOL","executie","dupa D","OUTCOME"),("outcomes","secondary_120","dict","idem la 120 s (descriptiv)","executie","dupa D","OUTCOME"),("outcomes","cost_x125 / latency_plus2","dict","stres taxe x1,25 / intrare la D+2 s","executie","dupa D","OUTCOME"),
    ("signals","H1 / H2 / H3","bool","semnal conform pragurilor DEV inghetate","eval","<D","PIT"),("signals","H1_v / H2_v / H3_v","float","valoarea trasaturii","eval","<D","PIT"),("signals","H*_elig","bool","eligibilitate (minime de cumparatori/swap-uri, trasatura definita)","eval","<D","PIT")]
with open(f"{OUT}/data_dictionary.csv","w",newline="") as f:
    w=csv.writer(f); w.writerow(["FILE","COLUMN","TYPE","FORMULA","SOURCE","EARLIEST_AVAILABILITY","POINT_IN_TIME_FEATURE_OR_OUTCOME"]); w.writerows(DD)
def hreport(h):
    r=R[h]; s=r["signals"] or {}; b=r["bootstrap"] or {}; m=r["matched"] or {}; c=r["complement"] or {}; u=r["unconditional_eligible"] or {}; g=r["gate"]
    L=[f"# {h} — {names[h]} — POST_HOC_HISTORICAL_RESEARCH",f"VERDICT = {r['verdict']}","",f"Praguri DEV inghetate (thresholds_frozen.json): {json.dumps(r['thresholds'])}",f"Eligibile VAL+CONF: {r['n_eligible_val_conf']}; semnale N = {s.get('N')} pe {s.get('mints')} mint-uri; DEV (descriptiv) N = {(r['DEV_signals_descriptive'] or {}).get('N')}, EV = {fmt((r['DEV_signals_descriptive'] or {}).get('EV'))}","",
       "| Set | N | EV SOL | mediana | PF | win | ex-best-1% | max cota mint | EV 09-03 | EV 09-04 |","|---|---|---|---|---|---|---|---|---|---|"]
    for name,st in (("SEMNALE",s),("matched",m),("complement",c),("neconditionat eligibil",u),("cost x1.25",r["cost_x125"] or {}),("latenta +2 s",r["latency_plus2"] or {}),("120 s (descriptiv)",r["secondary_120_descriptive"] or {})):
        L.append(f"| {name} | {st.get('N','')} | {fmt(st.get('EV'))} | {fmt(st.get('median'))} | {fmt(st.get('PF'),3)} | {fmt(st.get('win_rate'),3)} | {fmt(st.get('EX_BEST_1PCT'))} | {fmt(st.get('max_mint_share'),3)} | {fmt((st.get('by_day') or {}).get('2026-09-03'))} | {fmt((st.get('by_day') or {}).get('2026-09-04'))} |")
    L+=["",f"Bootstrap 10.000 (stratificat pe zi, mint-uri reesantionate): CI95 corectat (alpha/3) = {b.get('CI95_corrected')}, CI95 brut = {b.get('CI95_raw')}, p brut (unilateral) = {b.get('p_raw_one_sided')}, p Bonferroni = {b.get('p_bonferroni')}",f"Poarta: {json.dumps(g)}",f"Adversarial: {json.dumps(AD.get(h,{}),default=str)[:1200]}","","Limitare counterfactuala directionala: tranzactiile ulterioare ale altora sunt aplicate pe starea observata, nu pe starea modificata de pozitia noastra (overlay static). Fara txIndex: intrarea/iesirea dupa toate evenimentele cu ts <= X (conservator). Starile neancorate si rupturile de lant sunt excluse."]
    open(f"{OUT}/{ {'H1':'h1_cohort_rotation','H2':'h2_seller_overhang','H3':'h3_selective_buyer'}[h]}_report.md","w").write("\n".join(L))
for h in R: hreport(h)
# adversarial md
open(f"{OUT}/adversarial_review.md","w").write("# Revizuire adversariala (regulile inghetate nu au fost modificate)\n\n```\n"+json.dumps({k:v for k,v in AD.items()},indent=1,default=str)[:20000]+"\n```\n")
best=[h for h in R if R[h]["verdict"].startswith("HISTORICAL_PAPER_CANDIDATE")]
commit=subprocess.run(["git","rev-parse","HEAD"],capture_output=True,text=True).stdout.strip()
summ=[f"OVERNIGHT_RESEARCH_COMPLETE = YES","DEADLINE_REACHED = NO",f"CURRENT_COMMIT = {commit}","NEW_DATA_ACCESSED = NO","RPC_CALLS = 0","COLLECTORS_STARTED = NO","LIVE_TRADING_ENABLED = NO",f"DATA_INTEGRITY = OK (tape manifests {', '.join(v[:8]+'…' for v in IM['tape_day_manifests'].values())}; panel {PM['panel_content_sha256'][:12]}…; outcomes {OM['content_sha256'][:12]}…)",f"LEAKAGE_TESTS = {'PASS' if LT['feature_leakage']['PASS'] else 'FAIL'} ({LT['feature_leakage']['pools_tested']} pool-uri, {LT['feature_leakage']['violations']} incalcari)"]
for h in ("H1","H2","H3"):
    s=R[h]["signals"] or {}; b=R[h]["bootstrap"] or {}
    summ+=[f"{h}_VERDICT = {R[h]['verdict']}",f"{h}_N_SIGNALS = {s.get('N',0)}",f"{h}_N_MINTS = {s.get('mints',0)}",f"{h}_EV = {fmt(s.get('EV'))} SOL",f"{h}_PF = {fmt(s.get('PF'),3)}",f"{h}_CORRECTED_CI95 = {b.get('CI95_corrected')}"]
summ+=[f"BEST_HISTORICAL_CANDIDATE = {best[0] if best else 'NONE'}","MULTIPLE_TESTING_CORRECTION = Bonferroni x3 (p si CI la alpha/3); bootstrap 10.000 stratificat pe zi UTC cu reesantionarea mint-urilor",f"ADVERSARIAL_REVIEW = {'NO_DISCREPANCIES' if not AD.get('discrepancies') else 'DISCREPANCIES: '+str(AD['discrepancies'])}; determinism {AD.get('determinism')}; placebo +180 s {AD.get('placebo_decision_plus180')}",f"READY_FOR_FRESH_FORWARD_TEST = {'YES (paper, separat)' if best else 'NO'}","READY_FOR_LIVE_TRADING = NO",f"FINAL_REPORT_PATH = {OUT}/final_report.md","READY_FOR_EXTERNAL_REVIEW = YES"]
open(f"{OUT}/terminal_summary.txt","w").write("\n".join(summ))
fr=["# OVERNIGHT RESEARCH 2026-09-05 — RAPORT FINAL (POST_HOC_HISTORICAL_RESEARCH)","",f"Commit: {commit}. Fara Helius/RPC/API/WSS, fara colectoare, fara date noi, fara live. Partitie imutabila: DEV 09-02 / VAL 09-03 / CONF 09-04 (zile UTC ale CompleteEvent).","",
    f"## Date\nPanou: {PM['rows']} migrari cu istoric pre-migrare complet (cache m_pools, manifest sigilat), pe zile {PM['by_day']}; istoricul portofelelor: {PM['wallet_history_manifest']['wallets_with_history']} portofele relevante cu {PM['wallet_history_manifest']['events']} evenimente anterioare deciziei. Outcome-uri executabile: {OM['status_counts'].get('OK')} din {OM['rows']} ({json.dumps(OM['status_counts'])}).","",
    f"## Regula primara\nDecizie T0+60 s; intrare la starea ancorata de dupa toate evenimentele cu ts <= D; 0,25 SOL, cumparare exact-B sub buget; iesire +60 s (vanzare exact B, overlay static); taxe observate (taxa 0 => tier demonstrat); retea 0,00021 SOL; stari neancorate/rupturi excluse. Neconditionat VAL+CONF: {json.dumps({d:(v or {}).get('EV') for d,v in U['unconditional_by_day'].items()})}.","",
    "## Rezultate (semnale pe VAL+CONF; praguri DEV inghetate)","| Ipoteza | Verdict | N | mint-uri | EV SOL | PF | CI95 corectat | p Bonf. | EV 09-03 / 09-04 | matched | complement |","|---|---|---|---|---|---|---|---|---|---|---|"]
for h in ("H1","H2","H3"):
    s=R[h]["signals"] or {}; b=R[h]["bootstrap"] or {}; fr.append(f"| {h} {names[h]} | {R[h]['verdict']} | {s.get('N',0)} | {s.get('mints',0)} | {fmt(s.get('EV'))} | {fmt(s.get('PF'),3)} | {b.get('CI95_corrected')} | {b.get('p_bonferroni')} | {fmt((s.get('by_day') or {}).get('2026-09-03'))} / {fmt((s.get('by_day') or {}).get('2026-09-04'))} | {fmt((R[h]['matched'] or {}).get('EV'))} | {fmt((R[h]['complement'] or {}).get('EV'))} |")
fr+=["",f"Corectie multipla: {MT['correction']}. Teste de scurgere: {LT['feature_leakage']}.","",f"## Revizuire adversariala\nDeterminism: {AD.get('determinism')}; praguri identice cu cele inghetate: {AD.get('thresholds_match_frozen')}; portofele repetate: {AD.get('repeated_wallets')}; amestecare portofele: {AD.get('wallet_shuffle_within_comparable_pools')}; placebo +180 s: {AD.get('placebo_decision_plus180')}; scanare lookahead: {AD.get('source_lookahead_scan')}; reconciliere: {AD.get('count_reconciliation')}; discrepante: {AD.get('discrepancies')}.","",
    f"## Concluzie\nBEST_HISTORICAL_CANDIDATE = {best[0] if best else 'NONE'}. Nicio regula nu a fost modificata dupa vederea rezultatelor; regulile ramase in ledger ca esuate sunt pastrate. READY_FOR_LIVE_TRADING = NO."]
open(f"{OUT}/final_report.md","w").write("\n".join(fr))
open(f"{OUT}/README.md","w").write("# overnight_20260905\n\nCercetare istorica post-hoc pe date existente (fara RPC/date noi/live). Fisiere: integrity_manifest.json, fixed_family_preregistration.json (inainte de outcome), thresholds_frozen.json (DEV), data_dictionary.csv, leakage_tests.json, cohort_panel_manifest.json (randurile panoului contin portofele si raman locale), outcomes_manifest.json, h1/h2/h3 *_results.json + *_report.md, unconditional_results.json, multiple_testing_summary.json, adversarial_review.{json,md}, final_report.md, terminal_summary.txt, cod (wallet_history_pass.py, cohort_panel.py, fixed_family_eval.py, adversarial_review.py, make_docs.py), SHA256SUMS.\n")
files=sorted(p for p in glob.glob(f"{OUT}/*") if os.path.isfile(p) and not p.endswith("SHA256SUMS"))
open(f"{OUT}/SHA256SUMS","w").write("".join(f"{sha(p)}  {os.path.basename(p)}\n" for p in files)); print("docs written",len(files))
