"""CURVE2X V3 RECLAIM — inghetarea specificatiei INAINTE de orice outcome: definitii, cod (hash), split, trasaturi, modele, politica, costuri, teste, porti."""
import os,sys,json,time,hashlib
HERE=os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0,HERE); import v3_lib as V; L=V.L
def sha(p):
    h=hashlib.sha256()
    with open(p,"rb") as f:
        for c in iter(lambda:f.read(1<<20),b""): h.update(c)
    return h.hexdigest()
code={f:sha(os.path.join(HERE,f)) for f in ("v3_lib.py","build_v3.py","tests_v3.py","model_v3.py","watcher_v3.py","replay_v3.py","freeze_v3.py")}
v2=os.path.join(os.path.dirname(HERE),"curve2x_v2")
spec=dict(name="CURVE2X_V3_RECLAIM_AFTER_ABSORBED_PULLBACK",label="HISTORICAL_DEV_NOT_SEALED",frozen_at=time.strftime("%Y-%m-%d %H:%M:%S %Z"),sealed=False,preregistered_in_the_strict_sense=False,
 data=dict(source="cache-uri locale V2 derivate din banda existenta (curve + evenimente pool + flux)",tape_sha256sums=sha(os.path.join(v2,"TAPE_SHA256SUMS.txt")),tape_integrity_recheck="sha256sum -c: 0 nepotriviri (derived_v3/tape_integrity.log)",v2_sha256sums=sha(os.path.join(v2,"SHA256SUMS.txt")),v2_lib_sha256=sha(os.path.join(v2,"curve2x_lib.py")),v2_curves_cache_sha256=json.load(open(os.path.join(v2,"derived","curve2x_pass_manifest.json")))["curves_sha256"],v2_stream_sha256=json.load(open(os.path.join(v2,"derived","curve2x_pass_manifest.json")))["stream_sha256"],day_2026_09_01="ABSENT LOCAL (0 fisiere)",rpc_calls=0,new_data=False),
 code_sha256=code,
 definitions=dict(reference_position="0,25 SOL cumparati (exec_buy) la anchor; valoarea executabila V(t) = exec_sell cu overlay static al pozitiei de referinta la fiecare stare ulterioara",anchor="primul trade (post-stare) cu rezerva reala >= 40 % x 85 SOL, in fereastra create+1860 s, inainte de CompleteEvent",pullback="prima stare cu V <= 0,90 x maximul curent al lui V (de la anchor)",trough="minimul lui V dupa startul pullback-ului",reclaim="prima stare cu V >= trough + 0,75 x (max_pb - trough), in maximum 120 s de la startul pullback-ului; daca cele 120 s expira, episodul este abandonat, maximul curent se reseteaza la V si urmarirea continua",
   decision="o singura decizie per mint, la primul reclaim valid",entry="exec_buy 0,25 SOL la ultima stare cu slot <= decision_slot+3 (stres +5); NO_FILL_MIGRATED daca migrarea precede aterizarea",multi_state_same_slot="ordinea benzii (slot, seq, k)"),
 label_def=dict(kind="FIRST_PASSAGE",tp="valoare neta executabila >= +100 % (2,0 x gross)",sl="valoare neta executabila <= -35 % (0,65 x gross)",timeout_s=900,same_slot="SL castiga",exit_latency="+3 sloturi (stres +5), PnL la valoarea de aterizare",fees="curba 125 bp (mostenita V2); pool lp+protocol+creator observate per stare",network_cost_lamports=L.NET_COST,network_cost_status="PRESUPUNERE, declarat separat",cost_stress=1.25,migration="continuare in pool canonic cu splice demonstrabil (pool_prepare V2); altfel CROSS_MIGRATION_LABEL_UNAVAILABLE (exclus din evaluare, numarat)",gap="randuri cu orizont suprapus peste deconectari excluse"),
 features=dict(list=V.FEATS,state_baseline=V.STATE_FEATS,forbidden=["mint","pool","user","signature","timestamp absolut","alte identificatoare"],cross_mint_context="wallet_reuse_share: cumparatorii din reclaim vazuti cumparand alte lansari in ultimele 60 min (doar trecut)"),
 split=dict(requested="09-01 TRAIN / 09-02 CAL / 09-03 VAL / 09-04 CONF",deviation="09-01 NU exista local; pentru a pastra ordinea stricta cronologica si patru roluri: TRAIN = 09-02 (de la inceputul benzii), CAL = 09-03 00:00-12:00 UTC, VAL = 09-03 12:00-24:00 UTC, CONF = 09-04 (pana la oprirea colectorului). Niciun rand nu este mutat intre zile; ziua 09-03 este subdivizata dupa ora UTC (nu aleator). Un singur rand per mint.",train_end_utc="2026-09-03 00:00",cal_end_utc="2026-09-03 12:00",val_end_utc="2026-09-04 00:00",embargo_s=1800,random_split=False),
 models=dict(A="multinomial logistic L2 (V2 lib)",B="GBM depth-2 multiclass (V2 lib)",C="baseline logit doar state/headroom",calibration="vector scaling pe CAL",expected_net="GBM regresie pe PnL exact (TRAIN), LCB90 din sd rezidual pe chintile CAL",drivers="contributii standardizate din logit-ul companion (TP vs SL)"),
 model_selection=dict(on="CAL",order=["log loss","gap de calibrare in regiunea p_tp >= min(grila)","EV realizat in regiune"],tolerance_rel=0.005,tolerance_gap_abs=0.01),
 policy=dict(p_tp_grid=[0.25,0.30,0.35,0.40,0.45,0.50],universal=["EXPECTED_NET > 0"],min_mints_cal=30,choice="max LCB90 (bootstrap mint) al EV per mint pe CAL",actions=["REJECT","WATCH"],policy_enabled=False,paper_candidate_possible=False),
 gates=dict(min_mints_val_conf=100,min_mints_conf=30,ev_combined_positive=True,ci95_lower_positive=True,pf_min=1.30,ev_positive_val_and_conf=True,ex_best_1pct_positive=True,max_share_mint_creator_hour=0.20,stress_land5_positive=True,stress_cost125_positive=True,calibration_region_min_obs=30,calibration_gap_max_pp=8,beats_state_headroom_baseline=True,hour_diversity="max 50 % din semnale in aceeasi ora",tests="leakage, future mutation, same-slot ordering, one-decision-per-mint PASS"),
 max_verdict="HISTORICAL_PAPER_CANDIDATE_REQUIRES_FRESH_FORWARD",forbidden=["RPC/API/WSS/date noi","live trading","modificarea V1/V2","alte strategii in paralel","adrese brute"])
json.dump(spec,open(os.path.join(HERE,"frozen_spec.json"),"w"),indent=1,ensure_ascii=False); print("frozen_spec sha256",sha(os.path.join(HERE,"frozen_spec.json")))
