"""CURVE2X V3 — model_card.md, calibration.csv, terminal_signal_rows.txt, final_report.md, final_summary.json (din results.json si manifeste)."""
import os,json,csv,time
HERE=os.path.dirname(os.path.abspath(__file__)); R=json.load(open(os.path.join(HERE,"results.json"))); DM=json.load(open(os.path.join(HERE,"dataset_manifest.json"))); SP=json.load(open(os.path.join(HERE,"frozen_spec.json")))
LK=json.load(open(os.path.join(HERE,"leakage_report.json"))) if os.path.exists(os.path.join(HERE,"leakage_report.json")) else {}; RC=json.load(open(os.path.join(HERE,"replay_check.json"))) if os.path.exists(os.path.join(HERE,"replay_check.json")) else {}; TR=json.load(open(os.path.join(HERE,"test_results.json")))
SG=json.load(open(os.path.join(HERE,"signals_val_conf.json"))) if os.path.exists(os.path.join(HERE,"signals_val_conf.json")) else []
def f(x,d=4): return "n/a" if x is None or (isinstance(x,float) and x!=x) else (f"{x:.{d}f}" if isinstance(x,float) else str(x))
EV=R.get("evaluation",{}); g=R.get("gates",{}); pol=R.get("policy_selected"); sel=R.get("selection",{}).get("selected")
with open(os.path.join(HERE,"calibration.csv"),"w",newline="") as fh:
    w=csv.writer(fh); w.writerow(["segment","class","bin","n","pred","obs"])
    for c in R.get("candidates",[]):
        if c["kind"]==sel:
            for cls,key in (("TP_FIRST","rel_tp"),("SL_FIRST","rel_sl")):
                for b in c[key]: w.writerow(["CAL",cls,b["bin"],b["n"],f(b["pred"]),f(b["obs"])])
    for seg in ("VAL","CONF","VAL+CONF"):
        for b in (EV.get(seg,{}).get("all_rows") or {}).get("rel_tp",[]): w.writerow([seg,"TP_FIRST",b["bin"],b["n"],f(b["pred"]),f(b["obs"])])
def line(seg,var):
    s=EV.get(seg,{}).get(var) or {}; return f"| {seg} | {var} | {s.get('usable',0)} | {f(s.get('TP_FIRST_rate'),3)} | {f(s.get('SL_FIRST_rate'),3)} | {f(s.get('timeout_rate'),3)} | {f(s.get('EV'))} | {f(s.get('median'))} | {f(s.get('PF'),2)} | {s.get('CI95')} | {f(s.get('EX_BEST_1PCT'))} | {f(s.get('max_mint_share'),3)}/{f(s.get('max_creator_share'),3)}/{f(s.get('max_hour_share'),3)} |"
a=EV.get("VAL+CONF",{}); ARM={k:v for k,v in (a.get('all_rows') or {}).items() if k!='rel_tp'}; v=EV.get("VAL",{}).get("base",{}); c_=EV.get("CONF",{}).get("base",{}); ab=a.get("base",{})
card=[f"# CURVE2X_V3_RECLAIM_AFTER_ABSORBED_PULLBACK — model card (HISTORICAL_DEV_NOT_SEALED)","",f"Generat {time.strftime('%Y-%m-%d %H:%M %Z')}. Ipoteza unica; date deja inspectate (nimic sealed); zero RPC; policy_enabled=false; watcher-ul emite doar REJECT/WATCH.","",
 "## Date",f"- Mint-uri in cache {DM['mints_in_cache']}; N_ANCHORED {DM['N_ANCHORED']}; N_PULLBACKS {DM['N_PULLBACKS']}; N_RECLAIMS (decizii, o per mint) {DM['N_RECLAIMS']}; split {DM['by_split']}; zile {DM['by_day']}; gap {DM['gap_rows']}; migrate {DM['migrated']} (splice OK {DM['splice_ok']}, indisponibil {DM['splice_unavailable']}).",f"- Status etichete (0,25 SOL, 15M, base): {DM['status_base']}",f"- Split efectiv: {SP['split']['deviation']}",
 f"- Teste sintetice {sum(1 for t in TR['tests'].values() if t['pass_'])}/{len(TR['tests'])}; leakage_report PASS={LK.get('PASS')} (future mutation {LK.get('future_mutation',{}).get('identical')}/{LK.get('future_mutation',{}).get('sampled')}); replay agreement {RC.get('AUTOMATION_REPLAY_AGREEMENT')} ({RC.get('matching')}/{RC.get('batch_decisions')}), PAPER_CANDIDATE emise {RC.get('paper_candidates_emitted')}.","",
 "## Modele (selectie pe CAL: log loss -> calibrare -> EV)",f"- Prior TRAIN pe CAL: log loss {f(R.get('cal_prior_log_loss'))}; rate de baza {R.get('base_rates')}","| model | trasaturi | CAL log loss | CAL Brier | ECE TP | gap top | n top | EV realizat top |","|---|---|---|---|---|---|---|---|"]
for c in R.get("candidates",[]): card.append(f"| {c['kind']} | {c['feats']} | {f(c['log_loss'])} | {f(c['brier'])} | {f(c['ece_tp'],3)} | {f(c['top'].get('gap_tp'),3)} | {c['top'].get('n')} | {f(c.get('ev_cal_top'))} |")
card+=[f"- Selectat: **{sel}**; etape {R.get('selection')}",f"- Politica (prag pe CAL, grila {SP['policy']['p_tp_grid']}): {pol}; fezabila pe CAL: {R.get('policy_feasible_on_cal')}"+(f"; NOTA: {R.get('policy_note')}" if R.get('policy_note') else ""),"",
 "## Evaluare (o singura data; nivel de mint; bootstrap mint x zi)","| segment | varianta | mint-uri | TP | SL | timeout | EV SOL | mediana | PF | CI95 | EX_BEST_1% | max cota mint/creator/ora |","|---|---|---|---|---|---|---|---|---|---|---|---|"]
for seg in ("VAL","CONF","VAL+CONF"):
    for var in ("base","land5","cost125"): card.append(line(seg,var))
card+=["",f"- Calibrare in regiunea selectata (VAL+CONF): {a.get('selected_region_calibration')}",f"- Toate randurile VAL+CONF: {ARM}",f"- Baseline C (state/headroom) cu aceeasi politica: {a.get('baseline_C_same_policy')}; log loss C pe toate randurile {f(a.get('baseline_C_all_rows_log_loss'))}","","## Porti","| poarta | rezultat |","|---|---|"]+[f"| {k} | {x if isinstance(x,str) else ('PASS' if x else 'FAIL')} |" for k,x in g.items()]
card+=["",f"**FINAL_VERDICT = {R.get('FINAL_VERDICT')}** (maxim permis: HISTORICAL_PAPER_CANDIDATE_REQUIRES_FRESH_FORWARD). policy_enabled=false. READY_FOR_REAL_MONEY=NO. LIVE_TRADING_ENABLED=NO.","","## Limitari","- Date deja inspectate; 09-01 absent; un regim de ~2 zile; cost de retea presupus; overlay static; latenta presupusa; VQ implicit; taxa curbei mostenita din V2."]
open(os.path.join(HERE,"model_card.md"),"w").write("\n".join(card))
lines=[f"V3_RECLAIM | {R.get('FINAL_VERDICT')} | model {sel} | policy {pol} | model_hash {str(R.get('model_hash'))[:16]}.."]
for s in SG[:60]: lines.append(f"SIGNAL | MINT={s['mint_id']} | SEG={s['segment']} | DAY={s['day']} | PROGRESS={s['progress']:.2f} | P_TP_FIRST={s['p_tp']:.3f} | P_SL_FIRST={s['p_sl']:.3f} | P_TIMEOUT={s['p_to']:.3f} | EXPECTED_NET_SOL={s['ev']:+.4f} | EXPECTED_NET_LCB90={s['ev_lcb']:+.4f} | PREDICTION_UNCERTAINTY={s['uncertainty']:.3f} | TOP_POSITIVE_DRIVERS={','.join(s['top_positive'])} | TOP_RISK_DRIVERS={','.join(s['top_risk'])} | OUTCOME={s['state']} ({s['label_kind']}) | PNL={s['pnl']:+.4f} | ACTION=WATCH (policy_enabled=false)")
open(os.path.join(HERE,"terminal_signal_rows.txt"),"w").write("\n".join(lines)+"\n")
summ=dict(V3_COMPLETE="YES",N_ANCHORED=DM["N_ANCHORED"],N_PULLBACKS=DM["N_PULLBACKS"],N_RECLAIMS=DM["N_RECLAIMS"],N_TRAIN=DM["by_split"].get("TRAIN",0),N_CAL=DM["by_split"].get("CAL",0),N_VAL=DM["by_split"].get("VAL",0),N_CONF=DM["by_split"].get("CONF",0),MODEL_SELECTED=sel,POLICY_SELECTED=pol,TP_FIRST_RATE=ab.get("TP_FIRST_rate"),SL_FIRST_RATE=ab.get("SL_FIRST_rate"),EV_025_SOL=ab.get("EV"),PF_025_SOL=ab.get("PF"),CI95=ab.get("CI95"),EV_EX_BEST_1PCT=ab.get("EX_BEST_1PCT"),STRESS_5_SLOT_EV=(a.get("land5") or {}).get("EV"),STRESS_COST_125_EV=(a.get("cost125") or {}).get("EV"),CALIBRATION_GAP_SELECTED_REGION=(a.get("selected_region_calibration") or {}).get("gap_tp"),FINAL_VERDICT=R.get("FINAL_VERDICT"),POLICY_ENABLED=False,READY_FOR_FRESH_FORWARD=("YES_PAPER_ONLY" if R.get("FINAL_VERDICT")=="HISTORICAL_PAPER_CANDIDATE_REQUIRES_FRESH_FORWARD" else "NO"),READY_FOR_REAL_MONEY="NO",LIVE_TRADING_ENABLED="NO",gates=g,N_VAL_USABLE_SIGNALS=v.get("usable"),N_CONF_USABLE_SIGNALS=c_.get("usable"))
json.dump(summ,open(os.path.join(HERE,"final_summary.json"),"w"),indent=1,default=float)
rep=["# CURVE2X_V3_RECLAIM — raport final (HISTORICAL_DEV_NOT_SEALED)","",open(os.path.join(HERE,"hypothesis.md")).read(),"","## Rezultat",f"FINAL_VERDICT = {R.get('FINAL_VERDICT')}","",f"Decizii: {DM['N_RECLAIMS']} mint-uri cu reclaim valid din {DM['N_ANCHORED']} ancorate ({DM['N_PULLBACKS']} pullback-uri). Model {sel}, politica {pol}.",f"VAL: {v}",f"CONF: {c_}",f"VAL+CONF base: {ab}",f"Stres +5 sloturi: {(a.get('land5') or {}).get('EV')}; cost +25 %: {(a.get('cost125') or {}).get('EV')}",f"Porti: {g}","","## Comparatie cu V2 (prima intrare la landmark)","V2 (0,25 SOL, 15M, landmark 20-60 %): TP_FIRST ~19,7 %, SL_FIRST ~48,2 % pe toate randurile VAL+CONF; politica infezabila. V3 vezi tabelul de mai sus.","","Vezi model_card.md pentru detalii; toate cifrele sunt istorice, pe date deja inspectate. policy_enabled=false; READY_FOR_REAL_MONEY=NO; LIVE_TRADING_ENABLED=NO."]
open(os.path.join(HERE,"final_report.md"),"w").write("\n".join(rep)); print("\n".join(lines[:4]))
