"""V3 — remediation_report.md, final_summary.json (campuri remediate), results_original.json / dataset_manifest_original.json din results_remediated.json."""
import os,json,shutil
HERE=os.path.dirname(os.path.abspath(__file__)); R=json.load(open(os.path.join(HERE,"results_remediated.json"))); d=R["diff_vs_original"]; a=R["evaluation"]["VAL+CONF"]
f=lambda x,k=4:("n/a" if x is None else (f"{x:.{k}f}" if isinstance(x,float) else str(x)))
def row(name,s): return f"| {name} | {s.get('usable',0)} | {f(s.get('TP_FIRST_rate'),3)} | {f(s.get('SL_FIRST_rate'),3)} | {f(s.get('EV'))} | {f(s.get('PF'),2)} | {s.get('CI95')} | {f(s.get('EX_BEST_1PCT'))} |"
L=["# V3 RECLAIM — remediere (HISTORICAL_DEV_NOT_SEALED; fara reantrenare, fara cautare de prag)","",f"Model identic (hash {R['model_hash'][:16]}…), p_tp_min = 0,25. Corectii: (1) `migrated_in_window` = CompleteEvent exista SI complete_ts <= decizie + 900 s, altfel CURVE_ONLY; (2) limite de ordine fara transactionIndex: intrare = inainte de primul trade din slotul de aterizare si dupa fiecare trade din slot; iesire = ULTIMA stare strict inainte de exit_slot si fiecare stare succesiva din exit_slot (starile intermediare NU sunt pozitii plauzibile); primar = conservative; midpoint/optimistic raportate; CHAIN_BREAK exclus.","",
 "## Reparari",f"- splice-unavailable: original {d['splice_unavailable_original']} -> remediat {d['splice_unavailable_remediated']} => **{d['repaired_by_horizon_fix']} din 9 reparate**; migrate in orizont: {d['migrated_in_window_original']} -> {d['migrated_in_window_remediated']}.",f"- limite de ordine: {d['bounds_status']}; pozitii plauzibile de intrare: {d['entry_positions_hist']}.",f"- teste sintetice: original {d['tests_original']} -> remediat {d['tests_remediated']} (testul tautologic `label_independent_of_features` eliminat; adaugate: CompleteEvent dupa orizont, ordinea conservative<=midpoint<=optimistic, CHAIN_BREAK, semantica pozitiilor de iesire).","",
 "## VAL+CONF, 0,25 SOL, semnale P_TP >= 0,25 & EV > 0","| estimare | mint-uri | TP | SL | EV SOL | PF | CI95 | EX_BEST_1% |","|---|---|---|---|---|---|---|---|",row("V3-original (dupa toate trade-urile din slot)",d["val_conf_original_base"]),row("remediat: conservative (PRIMAR)",a["conservative"]),row("remediat: midpoint",a["midpoint"]),row("remediat: optimistic",a["optimistic"]),row("remediat: +5 sloturi, conservative",a["land5_conservative"]),row("remediat: cost +25 %, conservative",a["cost125_conservative"]),"",
 f"Calibrare in regiunea selectata (conservative): {a.get('selected_region_calibration')}","","## Porti (conservative)","| poarta | rezultat |","|---|---|"]+[f"| {k} | {v if isinstance(v,str) else ('PASS' if v else 'FAIL')} |" for k,v in R["gates"].items()]+["",f"**V3_REMEDIATED_VERDICT = {R['FINAL_VERDICT']}** (original: {d['verdict_original']}). policy_enabled=false; READY_FOR_REAL_MONEY=NO; LIVE_TRADING_ENABLED=NO."]
open(os.path.join(HERE,"remediation_report.md"),"w").write("\n".join(L)); shutil.copy(os.path.join(HERE,"original","results.json"),os.path.join(HERE,"results_original.json")); shutil.copy(os.path.join(HERE,"original","dataset_manifest.json"),os.path.join(HERE,"dataset_manifest_original.json"))
fs=json.load(open(os.path.join(HERE,"final_summary.json"))); fs.update(V3_REMEDIATED_VERDICT=R["FINAL_VERDICT"],REMEDIATION="vezi remediation_report.md / results_remediated.json (primar = conservative)",EV_025_SOL_CONSERVATIVE=a["conservative"]["EV"],PF_025_SOL_CONSERVATIVE=a["conservative"]["PF"],CI95_CONSERVATIVE=a["conservative"]["CI95"],SPLICE_UNAVAILABLE_REPAIRED=f"{d['repaired_by_horizon_fix']}/9",TESTS_ORIGINAL=d["tests_original"],TESTS_REMEDIATED=d["tests_remediated"]); json.dump(fs,open(os.path.join(HERE,"final_summary.json"),"w"),indent=1,default=float); print("remediation docs ok",d["repaired_by_horizon_fix"],d["tests_original"],d["tests_remediated"])
