"""Ingheata WALLET_FLOW_HAZARD_V1 inainte de outcome-uri: definitii, split, modele, grila restransa, costuri, porti, hash-uri de cod."""
import os,sys,json,time,hashlib
HERE=os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0,HERE); import wfh_lib as W
def sha(p):
    h=hashlib.sha256()
    with open(p,"rb") as f:
        for c in iter(lambda:f.read(1<<20),b""): h.update(c)
    return h.hexdigest()
v2=os.path.join(os.path.dirname(HERE),"curve2x_v2"); v3=os.path.join(os.path.dirname(HERE),"curve2x_v3_reclaim")
spec=dict(name="WALLET_FLOW_HAZARD_V1",label="HISTORICAL_HYPOTHESIS_GENERATION_NOT_SEALED",frozen_at=time.strftime("%Y-%m-%d %H:%M:%S %Z"),sealed=False,
 data=dict(source="cache-uri locale V2 (curve + pool + flux) si randurile de landmark V2; zero RPC; date deja inspectate",v2_curves_sha256=json.load(open(os.path.join(v2,"derived","curve2x_pass_manifest.json")))["curves_sha256"],v2_rows_sha256=json.load(open(os.path.join(v2,"build_manifest.json")))["rows_sha256"],v3_lib_sha256=sha(os.path.join(v3,"v3_lib.py"))),
 code_sha256={f:sha(os.path.join(HERE,f)) for f in ("wfh_lib.py","build_wfh.py","tests_wfh.py","model_wfh.py","freeze_wfh.py")},
 wallet_graph=dict(position="(portofel, mint): prima cumparare, sol_in/tok_in, sol_out/tok_out; marcarea inventarului ramas la ultima stare <= prima cumparare + 900 s (executabil, overlay static); TP proxy = pret max (vs/vt) in 900 s >= 2,1 x pretul mediu de intrare; realized_pnl = sol_out + marcare - sol_in; survived = pnl > -35 % din sol_in",maturity="maturity_ts = prima cumparare + 960 s; o statistica la timpul t foloseste doar pozitii cu maturity_ts <= t",creator="lansare maturizata la create + 1860 + 960 s: migrare, TP proxy pentru referinta 0,25 SOL la 20 % progres, cota vanduta de creator, EV proxy",forbidden_features=["wallet ID","mint ID","timestamp absolut"]),
 checkpoints=dict(type="landmark-uri de progres V2 (prima atingere)",grid_pct=[20,30,40,50,60],selection="un singur checkpoint per mint (prima decizie eligibila in ordinea landmark-urilor); checkpoint-ul si pragul se aleg EXCLUSIV pe TRAIN/CAL"),
 feature_blocks=W.BLOCKS,label_def=dict(kind="FIRST_PASSAGE (V3 lib, read-only)",tp="+100 % net",sl="-35 % net",horizon_s=900,same_slot="SL castiga",landing="+3 sloturi; PnL primar = conservative (limite de ordine: intrare inainte/dupa fiecare trade din slotul de aterizare; iesire = ultima stare inainte de exit_slot + starile din exit_slot); CHAIN_BREAK exclus; migrare doar in orizont; splice PumpSwap sau UNAVAILABLE",stress=["+5 sloturi conservative","cost x1,25 conservative"],network_cost="0,00021 SOL PRESUPUNERE"),
 models=dict(H="hazarde concurente discrete (bin 60 s x 15): multinomial logistic pe person-period cu covariate de intrare + covariate variabile in timp (value_ratio, net_flow, sell_vol) + bin; P_TP/P_SL = suma hazardelor cauza-specifice x supravietuire",B="GBM depth-2 multinomial static (TP/SL/TIMEOUT la 15 min)",C="logistic doar MARKET_STATE (baseline state/headroom)",deep_learning="NU (istoric cauzal per portofel insuficient)",calibration="vector scaling pe CAL"),
 policy=dict(one_entry_per_mint=True,p_tp_grid=[0.25,0.30,0.35],universal=["EV conservator prezis > 0"],checkpoint_grid=[20,30,40,50,60],selection="TRAIN/CAL: max LCB90 (bootstrap mint) al EV conservator per mint, >= 30 mint-uri pe CAL",exit_static="TP 2x / SL -35 % / timeout 15 min",exit_dynamic="iesire la sfarsitul bin-ului b>=2 cand h_TP(b) < h_TP(1) SI h_SL(b) > h_SL(1) (hazarde prezise cu covariate curente); PnL conservativ; comparat cu exitul static pe VAL/CONF FARA alegere",no_selection_on_val_conf=True),
 split=dict(train="2026-09-02 (de la inceputul benzii)",train_end_utc="2026-09-03 00:00",cal="09-03 00:00-12:00 UTC",cal_end_utc="2026-09-03 12:00",val="09-03 12:00-24:00 UTC",val_end_utc="2026-09-04 00:00",conf="09-04",embargo_s=1800,outcome_maturity_s=960,one_row_per_mint=True),
 gates=dict(min_signals_val_conf=100,min_conf=30,ev_conservative_gt=0,ci95_lower_gt=0,pf_min=1.30,val_and_conf_positive=True,land5_gt=0,cost125_gt=0,ex_best_1pct_gt=0,beats_v3_conservative=-0.014,beats_state_headroom_baseline=True,max_share_entity_hour_day=0.20,multiple_testing="Holm pe toate modelele x politicile de exit (3 x 2 = 6 teste ale EV>0)"),
 forbidden=["RPC/WSS/API","date noi","live","forward collection","alte praguri dupa VAL/CONF"])
json.dump(spec,open(os.path.join(HERE,"frozen_spec.json"),"w"),indent=1,ensure_ascii=False); print("WFH_SPEC_FROZEN",sha(os.path.join(HERE,"frozen_spec.json"))[:16])
