"""WALLET_FLOW_HAZARD_V1 — model_card.md, calibration.csv, final_summary.json, final_report.md (agregate; fara identificatori)."""
import os,json,csv,time
HERE=os.path.dirname(os.path.abspath(__file__)); R=json.load(open(os.path.join(HERE,"results.json"))); DM=json.load(open(os.path.join(HERE,"dataset_manifest.json"))); SP=json.load(open(os.path.join(HERE,"frozen_spec.json"))); TR=json.load(open(os.path.join(HERE,"test_results.json")))
f=lambda x,k=4:("n/a" if x is None or (isinstance(x,float) and x!=x) else (f"{x:.{k}f}" if isinstance(x,float) else str(x)))
sel=R["selected_model_on_cal"]; pol=R["policy_selected"]; EV=R["evaluation"]; g=R["gates"]
with open(os.path.join(HERE,"calibration.csv"),"w",newline="") as fh:
    w=csv.writer(fh); w.writerow(["model","bin","n","pred","obs"])
    for m,c in R["candidates"].items():
        for b in c.get("rel_tp",[]): w.writerow([m,b["bin"],b["n"],f(b["pred"]),f(b["obs"])])
def row(seg,m,ex):
    s=EV[seg][m][ex]; e=EV[seg][m]; return f"| {seg} | {m} | {ex} | {s.get('usable',0)} | {f(e.get('TP_rate'),3)} | {f(e.get('SL_rate'),3)} | {f(s.get('EV'))} | {f(s.get('median'))} | {f(s.get('PF'),2)} | {s.get('CI95')} | {f(s.get('EX_BEST_1PCT'))} | {f(s.get('p_one_sided'),3)} |"
card=[f"# WALLET_FLOW_HAZARD_V1 — model card (HISTORICAL_HYPOTHESIS_GENERATION_NOT_SEALED)","",f"Generat {time.strftime('%Y-%m-%d %H:%M %Z')}. Date deja inspectate; zero RPC; policy_enabled=false; nicio colectare forward.","",
 "## Date si graf cauzal",f"- Graf: {DM['wallet_graph']}; randuri {DM['rows']} ({DM['mints']} mint-uri), split {DM['by_split']}, landmark-uri {DM['by_landmark']}; status conservative {DM['status_conservative']}; gap {DM['gap_rows']}; cota randurilor cu istoric de portofel {f(DM['share_rows_with_wallet_history'],3)}.",f"- Teste: {sum(1 for t in TR['tests'].values() if t['pass_'])}/{TR['n_tests']} (graf cauzal, future mutation, permutare, fara identificatori, bin-uri de hazard, exit dinamic conservativ).","",
 "## Modele (selectie pe CAL)",f"- Prior TRAIN pe CAL log loss {f(R['cal_prior_log_loss'])}; person-periods TRAIN {R['person_periods_train']}","| model | CAL log loss | Brier | ECE TP | gap top | n top |","|---|---|---|---|---|---|"]+[f"| {m} | {f(c['log_loss'])} | {f(c['brier'])} | {f(c['ece_tp'],3)} | {f(c['gap_top'],3)} | {c['n_top']} |" for m,c in R["candidates"].items()]
card+=[f"- Selectat: **{sel}**; politica (TRAIN/CAL): checkpoint >= {pol['Lmin']} %, P_TP >= {pol['p_tp_min']}, EV prezis > 0; fezabila pe CAL: {R['policy_feasible_on_cal']}","","## Evaluare VAL/CONF (o singura data; PnL conservativ; exit static vs dinamic — fara alegere)","| segment | model | exit | semnale | TP | SL | EV SOL | mediana | PF | CI95 | EX_BEST_1% | p (EV>0) |","|---|---|---|---|---|---|---|---|---|---|---|---|"]
for seg in ("VAL","CONF","VAL+CONF"):
    for m in ("H","B","C"):
        for ex in ("static","dynamic"): card.append(row(seg,m,ex))
a=EV["VAL+CONF"][sel]; card+=["",f"- Stres (model {sel}, VAL+CONF): +5 sloturi conservative {f(a['land5'].get('EV'))}; cost +25 % {f(a['cost125'].get('EV'))}; calibrare in regiune {a.get('calibration_selected')}; exit-uri dinamice declansate {a.get('dynamic_exits_triggered')}; delta EV dinamic-static {f(a.get('dynamic_delta_EV'))}",f"- Holm (3 modele x 2 exit-uri): {R['holm']}","","## Porti","| poarta | rezultat |","|---|---|"]+[f"| {k} | {v if isinstance(v,str) else ('PASS' if v else 'FAIL')} |" for k,v in g.items()]+["",f"**FINAL_VERDICT = {R['FINAL_VERDICT']}**. policy_enabled=false; READY_FOR_FORWARD_PAPER = {'YES' if R['FINAL_VERDICT']!='NO_VERIFIED_EDGE' else 'NO'}; LIVE_TRADING_ENABLED = NO."]
open(os.path.join(HERE,"model_card.md"),"w").write("\n".join(card))
summ=dict(NEW_INFORMATION_VS_H3="YES (outcome-uri maturizate per portofel, cumparatori noi profitabili, hazardul inventarului cohortelor timpurii, outcome-uri ale creatorului, hazarde concurente + exit dinamic)",CAUSAL_WALLET_GRAPH_PASS=TR["all_pass"],N_SIGNALS=a["static"].get("usable",0),P_TP_FIRST=a.get("mean_P_TP"),P_SL_FIRST=a.get("mean_P_SL"),TP_FIRST_RATE=a.get("TP_rate"),SL_FIRST_RATE=a.get("SL_rate"),EV_CONSERVATIVE=a["static"].get("EV"),PF=a["static"].get("PF"),CI95=a["static"].get("CI95"),DYNAMIC_EXIT_DELTA=a.get("dynamic_delta_EV"),CONF_RESULT=EV["CONF"][sel]["static"],FINAL_VERDICT=R["FINAL_VERDICT"],READY_FOR_FORWARD_PAPER=("YES_PAPER_ONLY" if R["FINAL_VERDICT"]!="NO_VERIFIED_EDGE" else "NO"),LIVE_TRADING_ENABLED="NO",model=sel,policy=pol,gates=g,holm=R["holm"])
json.dump(summ,open(os.path.join(HERE,"final_summary.json"),"w"),indent=1,default=float)
open(os.path.join(HERE,"final_report.md"),"w").write("\n".join(["# WALLET_FLOW_HAZARD_V1 — raport final (HISTORICAL_HYPOTHESIS_GENERATION_NOT_SEALED)","",open(os.path.join(HERE,"hypothesis_comparison.md")).read(),"","## Rezultat",f"FINAL_VERDICT = {R['FINAL_VERDICT']}",f"Model {sel}, politica {pol}; VAL+CONF static conservativ: {a['static']}; dinamic: {a['dynamic']}; CONF: {EV['CONF'][sel]['static']}",f"Porti: {g}","Vezi model_card.md. policy_enabled=false; nicio colectare forward; LIVE_TRADING_ENABLED=NO."]))
print(json.dumps({k:summ[k] for k in ("N_SIGNALS","EV_CONSERVATIVE","PF","CI95","DYNAMIC_EXIT_DELTA","FINAL_VERDICT")},default=float))
