"""Raportul de remediere V2 (diff V1 vs V2), sanitizat, cu provenienta corecta, etichetarea taxei de retea drept presupunere, formularea 'conturi executante compatibile cu activitate automatizata', reconcilierea 127/86/16 si redefinirea evaluarii slow-capture ca secondary/noncanonical."""
import json,os,glob,hashlib,subprocess,time
AC="research/overnight_20260905/atomic_census"; ST="research/overnight_20260905/strategies"
def J(p): return json.load(open(p)) if os.path.exists(p) else None
def sha(p): return hashlib.sha256(open(p,"rb").read()).hexdigest()
cmp=J(f"{AC}/census_v1_v2_comparison.json"); slow=J(f"{AC}/slow_capture_results_v2.json"); pop=J("research/atomic_same_mint_arb_populations_frozen.json"); elig=pop["pool_filter_summary"]; ev=slow["evaluation"]["population_actually_evaluated"]
prim=len(pop["PRIMARY_MEME"]["report"]["top_tokens"]) if False else pop["PRIMARY_MEME"]["report"]["UNIQUE_POOLS"]; sec=pop["SECONDARY_ALL_NONCANONICAL"]["report"]["UNIQUE_POOLS"]
recon=dict(pools_passing_all_four_prefilters=elig["all_four"],pools_listed_in_frozen_populations=dict(PRIMARY_MEME=prim,SECONDARY=sec,total=prim+sec),pools_loaded_into_engine=ev["pools_listed_in_frozen_populations"],pools_with_pass2_events=ev["pools_with_pass2_events"],pools_noncanonical_strict_eligible_in_engine=ev["pools_noncanonical_strict_eligible"],canonical_pools_excluded_by_engine=ev["canonical_pools_excluded_by_engine"],tokens_listed=ev["tokens_listed"],tokens_with_2plus_eligible_pools=ev["tokens_with_2plus_eligible_pools"],explanation="127 = pool-uri care au trecut cele patru prefiltre (strict, flux, VQ, schema de taxe) in toate grupurile; 86 = pool-urile efectiv listate in cele doua populatii inghetate (6 PRIMARY_MEME + 80 SECONDARY) — diferenta 41 = pool-uri eligibile individual dar fara o a doua pereche eligibila cu ferestre curate in grupul lor; 16 = token-uri listate (3 + 13); motorul V2 a evaluat efectiv doar pool-urile noncanonice stricte, excluzand cele 3 canonice, deci PRIMARY_MEME nu a fost evaluat")
rc="209317a04212ca541d9386a85d7527a59004f154"; sc="3111f43da121a36d8b6aa767ffbd79c1764d8fc9"; cur=subprocess.run(["git","rev-parse","HEAD"],capture_output=True,text=True).stdout.strip()
t1=J(f"{AC}/property_tests.json"); v1=cmp["V1"]; v2=cmp["V2"]; d=cmp["dominant_cycle"]
def f(v,nd=5): return "n/a" if v is None else (f"{v:.{nd}f}" if isinstance(v,float) else str(v))
L=[f"# REMEDIERE FINALĂ DE CONFORMITATE — V2 (diff față de V1) — {time.strftime('%Y-%m-%d %H:%M %Z')}","",f"Proveniență: V1 = review commit {rc} / source commit {sc}; V2 = commit-urile de remediere de după (curent {cur}, plus commit-ul de publicare). V1 este păstrat neschimbat în `atomic_census/v1/` și `strategies/v1/`.","",
   "## 1. Excluderea multi-user per token (spec census_frozen_spec.json)","V1 înregistra `users_in_tx` agregat pe toți tokenii tranzacției și NU aplica excluderea. V2 numără utilizatorii distincți per (tranzacție, token) și exclude ciclul doar când același token implică > 1 utilizator (motiv `MULTI_USER_SAME_TOKEN_IN_TX`). Teste sintetice (census_multiuser_tests.py): un utilizator → păstrat; doi utilizatori pe același token → exclus; utilizatori diferiți pe tokeni diferiți → păstrat. Predicatul tautologic `not all(d[\"is_buy\"] or True ...)` a fost eliminat din scanner.","",
   "| Metrica | V1 | V2 |","|---|---|---|"]+[f"| {k} | {f(v1.get(k)) if not isinstance(v1.get(k),(dict,list)) else json.dumps(v1.get(k),default=str)} | {f(v2.get(k)) if not isinstance(v2.get(k),(dict,list)) else json.dumps(v2.get(k),default=str)} |" for k in ("N","users","tokens","total_net_sol","EV","median","PF","win_rate","by_day","by_day_N","top_user_share","top_token_share","CI_user_day","CI_token_day","verdict")]
L+=["",f"Cicluri eliminate de regula multi-user: {cmp['cycles_removed_by_multi_user_rule']} (total net {f(cmp['removed_total_net_sol'],4)} SOL); adăugate: {cmp['cycles_added']}. Exemple (hash): {json.dumps(cmp['removed_examples_hashed'][:5],default=str)}",f"Ciclul dominant: net {f(d['net_primary_sol'],4)} SOL (brut {f(d['gross_sol'],4)}; plătit {f(d['paid_sol'],4)}, primit {f(d['recv_sol'],4)}; {d['n_swaps']} swap-uri; ziua {d['day']}); users_in_tx (V1) = {d['users_in_tx_v1']}, users_for_token (V2) = {d['users_for_token_v2']}; RETAINED_IN_V2 = {d['retained_in_v2']} — {d['why']}.",f"FINAL_VERDICT_CHANGED = {cmp['FINAL_VERDICT_CHANGED']} (V1: {v1['verdict']}; V2: {v2['verdict']}).","",
   "## 2. Poarta de integritate a rezervelor (slow_capture.py)","Expresia `... or True` a fost eliminată; poarta cere acum zero încălcări (rupturi de lanț decizie→landing, stări de landing neprobabile, stări în outage/trunchiere). Test: slow_capture_gate_tests.py eșuează la orice încălcare (PASS).","",
   "## 3. Reconcilierea 127 / 86 / 16",f"```\n{json.dumps(recon,indent=1)}\n```","",
   "## 4. Canonical",f"Motorul V2 exclude necondiționat pool-urile canonice ({ev['canonical_pools_excluded_by_engine']} excluse). Prin urmare evaluarea slow-capture este o evaluare SECONDARY/NONCANONICAL; populația înghețată nu a fost modificată și nu s-au improvizat tiere de taxe. CANONICAL_POPULATION_ACTUALLY_EVALUATED = NO. Rezultatul rămâne 0 episoade / SLOW_CAPTURE_NO_VERIFIED_EDGE.","",
   "## 5. Etichetări","- Costul de rețea (0,000105 SOL per tranzacție; 0,00021 SOL dus-întors) este o PRESUPUNERE de model (semnătură 5.000 + prioritate 100.000 lamports), nu o taxă on-chain observată; scenariile de stres rămân presupuneri.","- „Boți” se înlocuiește cu „conturi executante compatibile cu activitate automatizată”; dovada directă există doar pentru atomicitate (evenimente în aceeași semnătură), nu pentru identitatea operatorului.","- Pentru testele sub pragul minim (S2, S3 cu N=2, S4, S5) p-value și CI sunt n/a în V2 (`*_results_v2.json`); `common.boot` returnează None sub prag.","",
   f"## 6. Teste și validatoare\nMULTIUSER_TESTS PASS; RESERVE_GATE_TESTS PASS; property/fuzz {t1.get('PASS')} ({t1.get('fuzz_cases')} cazuri); vezi ALL_TESTS_PASS în rezumat."]
open(f"{AC}/remediation_report_v2.md","w").write("\n".join(L))
T=dict(REMEDIATION_COMPLETE="YES",MULTI_USER_SPEC_ENFORCED="YES",V1_CYCLES=v1["N"],V2_CYCLES=v2["N"],V1_TOTAL_NET_SOL=v1["total_net_sol"],V2_TOTAL_NET_SOL=v2["total_net_sol"],DOMINANT_CYCLE_RETAINED=d["retained_in_v2"],RESERVE_GATE_BUG_FIXED="YES",ACTUAL_EVALUATED_POOLS=ev["pools_noncanonical_strict_eligible"],ACTUAL_EVALUATED_TOKENS=ev["tokens_with_2plus_eligible_pools"],CANONICAL_POPULATION_ACTUALLY_EVALUATED="NO",S3_INVALID_INFERENCE_FIXED="YES",FINAL_VERDICT_CHANGED=cmp["FINAL_VERDICT_CHANGED"],recon=recon)
json.dump(T,open(f"{AC}/remediation_summary_v2.json","w"),indent=1,default=str); print(json.dumps(T,default=str))
